### ISSUE TITLE
我看了下iossdb的代码，有两个问题问下

### ISSUE THREAD

**Issue by gamelezi** [lessos/lessgo#5]
1.代码中对于所有参数总和大小的限制是4M（注释中却写着10M），这点不是很懂。
2.根据现在的SSDB文档，现在应该是31M
3.连接池通过一个chan实现了线程安全，所以我认为这个ssdb客户端可以在多线程（或者协程）环境下使用，是这样么？

**Comment by eryx** [comment]
@gamelezi 
1. 定义为 4MB 更多因为保守留有余地(实际在业务层，建议控制 Value 大小，这样对于大数据量下数据引擎的性能有好处);  另方面 iossdb.Batch() 执行多key/value 时理论上不限制大小，大于4MB 的 cmds 集合会被自动拆分多个子 cmds 依次提交，并合并结果。
2. 10MB的定义在 http://ssdb.io/docs/php/index.html 中的 batch()/exec() 中
3. 连接池理论上线程安全，但你的业务系统调用时需要考虑并发读写的情况。比如，多个 channel 同时对同一个 key 进行读写，对于 iossdb 和 ssdb-server 当然没有问题，但是你的业务系统逻辑就可能出错，这个你需要单独考虑。
